"""Auto-generated from ATS-Friendly-Resume-Analyzer's default_skills.sql --
a curated dictionary of skills with common aliases (e.g. "JS" -> "javascript")
used for skill-coverage matching between a resume and a job description."""

SKILLS = [
    {"name": 'php', "category": 'programming', "aliases": ['php', 'php8', 'php7']},
    {"name": 'python', "category": 'programming', "aliases": ['python', 'python3', 'py']},
    {"name": 'javascript', "category": 'programming', "aliases": ['javascript', 'js', 'ecmascript', 'es6', 'es2015']},
    {"name": 'typescript', "category": 'programming', "aliases": ['typescript', 'ts']},
    {"name": 'java', "category": 'programming', "aliases": ['java', 'j2ee', 'jdk']},
    {"name": 'c++', "category": 'programming', "aliases": ['c++', 'cpp', 'cplusplus']},
    {"name": 'c#', "category": 'programming', "aliases": ['c#', 'csharp', 'c sharp']},
    {"name": 'c', "category": 'programming', "aliases": ['c programming', 'ansi c']},
    {"name": 'ruby', "category": 'programming', "aliases": ['ruby', 'rb']},
    {"name": 'go', "category": 'programming', "aliases": ['go', 'golang']},
    {"name": 'rust', "category": 'programming', "aliases": ['rust', 'rustlang']},
    {"name": 'swift', "category": 'programming', "aliases": ['swift', 'swiftui']},
    {"name": 'kotlin', "category": 'programming', "aliases": ['kotlin', 'kt']},
    {"name": 'scala', "category": 'programming', "aliases": ['scala']},
    {"name": 'r', "category": 'programming', "aliases": ['r programming', 'r language', 'rlang']},
    {"name": 'perl', "category": 'programming', "aliases": ['perl']},
    {"name": 'sql', "category": 'programming', "aliases": ['sql', 'structured query language']},
    {"name": 'html', "category": 'programming', "aliases": ['html', 'html5']},
    {"name": 'css', "category": 'programming', "aliases": ['css', 'css3', 'stylesheet']},
    {"name": 'bash', "category": 'programming', "aliases": ['bash', 'shell script', 'shell scripting']},
    {"name": 'powershell', "category": 'programming', "aliases": ['powershell', 'ps1']},
    {"name": 'dart', "category": 'programming', "aliases": ['dart']},
    {"name": 'lua', "category": 'programming', "aliases": ['lua']},
    {"name": 'matlab', "category": 'programming', "aliases": ['matlab']},
    {"name": 'objective-c', "category": 'programming', "aliases": ['objective-c', 'objc', 'objective c']},
    {"name": 'react', "category": 'framework', "aliases": ['react', 'reactjs', 'react.js']},
    {"name": 'angular', "category": 'framework', "aliases": ['angular', 'angularjs', 'angular.js']},
    {"name": 'vue', "category": 'framework', "aliases": ['vue', 'vuejs', 'vue.js']},
    {"name": 'nextjs', "category": 'framework', "aliases": ['nextjs', 'next.js', 'next']},
    {"name": 'nuxtjs', "category": 'framework', "aliases": ['nuxtjs', 'nuxt.js', 'nuxt']},
    {"name": 'svelte', "category": 'framework', "aliases": ['svelte', 'sveltekit']},
    {"name": 'django', "category": 'framework', "aliases": ['django']},
    {"name": 'flask', "category": 'framework', "aliases": ['flask']},
    {"name": 'fastapi', "category": 'framework', "aliases": ['fastapi', 'fast api']},
    {"name": 'laravel', "category": 'framework', "aliases": ['laravel']},
    {"name": 'symfony', "category": 'framework', "aliases": ['symfony']},
    {"name": 'codeigniter', "category": 'framework', "aliases": ['codeigniter', 'ci']},
    {"name": 'spring', "category": 'framework', "aliases": ['spring', 'spring boot', 'springboot']},
    {"name": 'express', "category": 'framework', "aliases": ['express', 'expressjs', 'express.js']},
    {"name": 'rails', "category": 'framework', "aliases": ['rails', 'ruby on rails', 'ror']},
    {"name": 'dotnet', "category": 'framework', "aliases": ['dotnet', '.net', 'asp.net', 'dot net']},
    {"name": 'nodejs', "category": 'framework', "aliases": ['nodejs', 'node.js', 'node']},
    {"name": 'jquery', "category": 'framework', "aliases": ['jquery']},
    {"name": 'bootstrap', "category": 'framework', "aliases": ['bootstrap']},
    {"name": 'tailwindcss', "category": 'framework', "aliases": ['tailwindcss', 'tailwind', 'tailwind css']},
    {"name": 'flutter', "category": 'framework', "aliases": ['flutter']},
    {"name": 'react native', "category": 'framework', "aliases": ['react native', 'react-native']},
    {"name": 'electron', "category": 'framework', "aliases": ['electron', 'electronjs']},
    {"name": 'spring boot', "category": 'framework', "aliases": ['spring boot', 'springboot']},
    {"name": 'hibernate', "category": 'framework', "aliases": ['hibernate']},
    {"name": 'tensorflow', "category": 'framework', "aliases": ['tensorflow', 'tf']},
    {"name": 'pytorch', "category": 'framework', "aliases": ['pytorch', 'torch']},
    {"name": 'keras', "category": 'framework', "aliases": ['keras']},
    {"name": 'pandas', "category": 'framework', "aliases": ['pandas']},
    {"name": 'numpy', "category": 'framework', "aliases": ['numpy']},
    {"name": 'scikit-learn', "category": 'framework', "aliases": ['scikit-learn', 'sklearn', 'scikit learn']},
    {"name": 'mysql', "category": 'database', "aliases": ['mysql', 'my sql']},
    {"name": 'postgresql', "category": 'database', "aliases": ['postgresql', 'postgres', 'psql', 'pgsql']},
    {"name": 'mongodb', "category": 'database', "aliases": ['mongodb', 'mongo']},
    {"name": 'redis', "category": 'database', "aliases": ['redis']},
    {"name": 'elasticsearch', "category": 'database', "aliases": ['elasticsearch', 'elastic search', 'elastic']},
    {"name": 'sqlite', "category": 'database', "aliases": ['sqlite', 'sqlite3']},
    {"name": 'oracle', "category": 'database', "aliases": ['oracle', 'oracle db', 'oracle database']},
    {"name": 'sql server', "category": 'database', "aliases": ['sql server', 'mssql', 'microsoft sql server']},
    {"name": 'dynamodb', "category": 'database', "aliases": ['dynamodb', 'dynamo db', 'dynamo']},
    {"name": 'cassandra', "category": 'database', "aliases": ['cassandra', 'apache cassandra']},
    {"name": 'firebase', "category": 'database', "aliases": ['firebase', 'firestore']},
    {"name": 'mariadb', "category": 'database', "aliases": ['mariadb', 'maria db']},
    {"name": 'couchdb', "category": 'database', "aliases": ['couchdb', 'couch db']},
    {"name": 'neo4j', "category": 'database', "aliases": ['neo4j', 'neo 4j']},
    {"name": 'git', "category": 'tool', "aliases": ['git', 'github', 'gitlab', 'bitbucket']},
    {"name": 'docker', "category": 'tool', "aliases": ['docker', 'dockerfile', 'docker-compose']},
    {"name": 'kubernetes', "category": 'tool', "aliases": ['kubernetes', 'k8s', 'kube']},
    {"name": 'jenkins', "category": 'tool', "aliases": ['jenkins', 'jenkins ci']},
    {"name": 'terraform', "category": 'tool', "aliases": ['terraform', 'tf']},
    {"name": 'ansible', "category": 'tool', "aliases": ['ansible']},
    {"name": 'webpack', "category": 'tool', "aliases": ['webpack']},
    {"name": 'vite', "category": 'tool', "aliases": ['vite']},
    {"name": 'nginx', "category": 'tool', "aliases": ['nginx']},
    {"name": 'apache', "category": 'tool', "aliases": ['apache', 'apache http', 'httpd']},
    {"name": 'jira', "category": 'tool', "aliases": ['jira', 'atlassian jira']},
    {"name": 'confluence', "category": 'tool', "aliases": ['confluence']},
    {"name": 'postman', "category": 'tool', "aliases": ['postman']},
    {"name": 'swagger', "category": 'tool', "aliases": ['swagger', 'openapi']},
    {"name": 'grafana', "category": 'tool', "aliases": ['grafana']},
    {"name": 'prometheus', "category": 'tool', "aliases": ['prometheus']},
    {"name": 'ci/cd', "category": 'tool', "aliases": ['ci/cd', 'ci cd', 'continuous integration', 'continuous deployment']},
    {"name": 'linux', "category": 'tool', "aliases": ['linux', 'unix', 'ubuntu', 'centos', 'debian']},
    {"name": 'maven', "category": 'tool', "aliases": ['maven', 'apache maven']},
    {"name": 'gradle', "category": 'tool', "aliases": ['gradle']},
    {"name": 'npm', "category": 'tool', "aliases": ['npm', 'node package manager']},
    {"name": 'yarn', "category": 'tool', "aliases": ['yarn']},
    {"name": 'pip', "category": 'tool', "aliases": ['pip']},
    {"name": 'composer', "category": 'tool', "aliases": ['composer']},
    {"name": 'vagrant', "category": 'tool', "aliases": ['vagrant']},
    {"name": 'puppet', "category": 'tool', "aliases": ['puppet']},
    {"name": 'chef', "category": 'tool', "aliases": ['chef']},
    {"name": 'selenium', "category": 'tool', "aliases": ['selenium', 'selenium webdriver']},
    {"name": 'cypress', "category": 'tool', "aliases": ['cypress']},
    {"name": 'jest', "category": 'tool', "aliases": ['jest']},
    {"name": 'phpunit', "category": 'tool', "aliases": ['phpunit']},
    {"name": 'pytest', "category": 'tool', "aliases": ['pytest']},
    {"name": 'figma', "category": 'tool', "aliases": ['figma']},
    {"name": 'photoshop', "category": 'tool', "aliases": ['photoshop', 'adobe photoshop']},
    {"name": 'vs code', "category": 'tool', "aliases": ['vs code', 'visual studio code', 'vscode']},
    {"name": 'aws', "category": 'cloud', "aliases": ['aws', 'amazon web services', 'amazon cloud']},
    {"name": 'azure', "category": 'cloud', "aliases": ['azure', 'microsoft azure', 'ms azure']},
    {"name": 'gcp', "category": 'cloud', "aliases": ['gcp', 'google cloud', 'google cloud platform']},
    {"name": 'heroku', "category": 'cloud', "aliases": ['heroku']},
    {"name": 'digitalocean', "category": 'cloud', "aliases": ['digitalocean', 'digital ocean']},
    {"name": 'vercel', "category": 'cloud', "aliases": ['vercel']},
    {"name": 'netlify', "category": 'cloud', "aliases": ['netlify']},
    {"name": 'cloudflare', "category": 'cloud', "aliases": ['cloudflare', 'cloud flare']},
    {"name": 'lambda', "category": 'cloud', "aliases": ['lambda', 'aws lambda', 'serverless']},
    {"name": 's3', "category": 'cloud', "aliases": ['s3', 'aws s3', 'amazon s3']},
    {"name": 'ec2', "category": 'cloud', "aliases": ['ec2', 'aws ec2']},
    {"name": 'cloudfront', "category": 'cloud', "aliases": ['cloudfront', 'aws cloudfront']},
    {"name": 'machine learning', "category": 'data', "aliases": ['machine learning', 'ml']},
    {"name": 'deep learning', "category": 'data', "aliases": ['deep learning', 'dl']},
    {"name": 'artificial intelligence', "category": 'data', "aliases": ['artificial intelligence', 'ai']},
    {"name": 'data science', "category": 'data', "aliases": ['data science']},
    {"name": 'data analysis', "category": 'data', "aliases": ['data analysis', 'data analytics']},
    {"name": 'data engineering', "category": 'data', "aliases": ['data engineering']},
    {"name": 'big data', "category": 'data', "aliases": ['big data']},
    {"name": 'hadoop', "category": 'data', "aliases": ['hadoop', 'apache hadoop']},
    {"name": 'spark', "category": 'data', "aliases": ['spark', 'apache spark', 'pyspark']},
    {"name": 'tableau', "category": 'data', "aliases": ['tableau']},
    {"name": 'power bi', "category": 'data', "aliases": ['power bi', 'powerbi', 'microsoft power bi']},
    {"name": 'nlp', "category": 'data', "aliases": ['nlp', 'natural language processing']},
    {"name": 'computer vision', "category": 'data', "aliases": ['computer vision', 'cv', 'image recognition']},
    {"name": 'etl', "category": 'data', "aliases": ['etl', 'extract transform load']},
    {"name": 'rest api', "category": 'api', "aliases": ['rest api', 'restful', 'rest', 'restful api']},
    {"name": 'graphql', "category": 'api', "aliases": ['graphql', 'graph ql']},
    {"name": 'grpc', "category": 'api', "aliases": ['grpc', 'g-rpc']},
    {"name": 'websocket', "category": 'api', "aliases": ['websocket', 'websockets', 'ws']},
    {"name": 'oauth', "category": 'api', "aliases": ['oauth', 'oauth2', 'oauth 2.0']},
    {"name": 'jwt', "category": 'api', "aliases": ['jwt', 'json web token', 'json web tokens']},
    {"name": 'soap', "category": 'api', "aliases": ['soap', 'soap api']},
    {"name": 'microservices', "category": 'api', "aliases": ['microservices', 'micro services']},
    {"name": 'communication', "category": 'soft_skill', "aliases": ['communication', 'communication skills']},
    {"name": 'teamwork', "category": 'soft_skill', "aliases": ['teamwork', 'team work', 'team player', 'collaboration']},
    {"name": 'leadership', "category": 'soft_skill', "aliases": ['leadership', 'team lead', 'team leadership']},
    {"name": 'problem solving', "category": 'soft_skill', "aliases": ['problem solving', 'problem-solving', 'analytical thinking']},
    {"name": 'time management', "category": 'soft_skill', "aliases": ['time management', 'time-management']},
    {"name": 'adaptability', "category": 'soft_skill', "aliases": ['adaptability', 'flexible', 'flexibility']},
    {"name": 'critical thinking', "category": 'soft_skill', "aliases": ['critical thinking', 'critical-thinking']},
    {"name": 'project management', "category": 'soft_skill', "aliases": ['project management', 'pm']},
    {"name": 'agile', "category": 'soft_skill', "aliases": ['agile', 'agile methodology', 'scrum', 'kanban']},
    {"name": 'mentoring', "category": 'soft_skill', "aliases": ['mentoring', 'coaching', 'mentorship']},
    {"name": 'responsive design', "category": 'design', "aliases": ['responsive design', 'responsive web design', 'rwd']},
    {"name": 'ux design', "category": 'design', "aliases": ['ux design', 'ux', 'user experience']},
    {"name": 'ui design', "category": 'design', "aliases": ['ui design', 'ui', 'user interface']},
    {"name": 'design patterns', "category": 'design', "aliases": ['design patterns']},
    {"name": 'oop', "category": 'design', "aliases": ['oop', 'object oriented programming', 'object-oriented']},
    {"name": 'mvc', "category": 'design', "aliases": ['mvc', 'model view controller']},
    {"name": 'tdd', "category": 'design', "aliases": ['tdd', 'test driven development', 'test-driven']},
    {"name": 'solid', "category": 'design', "aliases": ['solid', 'solid principles']},
    {"name": 'clean architecture', "category": 'design', "aliases": ['clean architecture']},
    {"name": 'ddd', "category": 'design', "aliases": ['ddd', 'domain driven design']},
    {"name": 'cybersecurity', "category": 'security', "aliases": ['cybersecurity', 'cyber security', 'information security']},
    {"name": 'penetration testing', "category": 'security', "aliases": ['penetration testing', 'pen testing', 'pentest']},
    {"name": 'encryption', "category": 'security', "aliases": ['encryption', 'cryptography']},
    {"name": 'owasp', "category": 'security', "aliases": ['owasp', 'owasp top 10']},
    {"name": 'sso', "category": 'security', "aliases": ['sso', 'single sign-on', 'single sign on']},
    {"name": 'network security', "category": 'security', "aliases": ['network security']},
]
